"""Generated firmware availability catalogue."""

# Generated by scripts/generate_firmware_version_header.py.
# Edit firmware/firmware-versions.json, not this file.

from typing import Final

FIRMWARE_CATALOG: Final = {
    "v1": {"name": "Maintained legacy", "sketch": "FireAngelNano", "version": "1.0.0"},
    "v2": {"name": "Protocol V2", "sketch": "FireAngelNanoV2", "version": "2.0.1"},
}
