"""Generate or validate firmware version artifacts from metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]
METADATA = REPOSITORY / "firmware" / "firmware-versions.json"
HEADER = REPOSITORY / "firmware" / "Arduino" / "FireAngelNanoV2" / "firmware_version.h"
INTEGRATION_CATALOG = (
    REPOSITORY / "custom_components" / "fireangel_pro_connected" / "firmware_catalog.py"
)


def expected_header() -> str:
    """Return the generated header content for the metadata's V2 version."""
    metadata = json.loads(METADATA.read_text())
    version = metadata["v2"]["version"]
    return (
        "// Generated by scripts/generate_firmware_version_header.py.\n"
        "// Edit firmware/firmware-versions.json, not this file.\n"
        "#pragma once\n\n"
        f'#define WISAFE_FIRMWARE_VERSION "{version}"\n'
    )


def expected_integration_catalog() -> str:
    """Return the generated integration firmware catalogue."""
    metadata = json.loads(METADATA.read_text())
    catalog = (
        "{\n"
        + "".join(
            f'    "{key}": {json.dumps(metadata[key], sort_keys=True)},\n'
            for key in sorted(metadata)
        )
        + "}"
    )
    return (
        '"""Generated firmware availability catalogue."""\n\n'
        "# Generated by scripts/generate_firmware_version_header.py.\n"
        "# Edit firmware/firmware-versions.json, not this file.\n\n"
        "from typing import Final\n\n"
        f"FIRMWARE_CATALOG: Final = {catalog}\n"
    )


def main() -> int:
    """Write generated artifacts or fail if checked-in copies are stale."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated_files = {
        HEADER: expected_header(),
        INTEGRATION_CATALOG: expected_integration_catalog(),
    }
    if args.check:
        stale = [
            path.relative_to(REPOSITORY)
            for path, expected in generated_files.items()
            if not path.is_file() or path.read_text() != expected
        ]
        if stale:
            raise SystemExit(
                "Generated firmware version files are stale "
                f"({', '.join(map(str, stale))}); run "
                "python scripts/generate_firmware_version_header.py"
            )
        return 0
    for path, expected in generated_files.items():
        path.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
