"""Generate or validate the AVR firmware version header from metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]
METADATA = REPOSITORY / "firmware" / "firmware-versions.json"
HEADER = REPOSITORY / "firmware" / "Arduino" / "FireAngelNanoV2" / "firmware_version.h"


def expected_header() -> str:
    """Return the generated header content for the metadata's V2 version."""
    metadata = json.loads(METADATA.read_text())
    version = metadata["v2"]["version"]
    return (
        "// Generated by scripts/generate_firmware_version_header.py.\n"
        "// Edit firmware/firmware-versions.json, not this file.\n"
        "#pragma once\n\n"
        f'#define WISAFE_FIRMWARE_VERSION "{version}"\n'
    )


def main() -> int:
    """Write the header or fail if the checked-in header is stale."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = expected_header()
    if args.check:
        if not HEADER.is_file() or HEADER.read_text() != expected:
            raise SystemExit(
                "Firmware version header is stale; run "
                "python scripts/generate_firmware_version_header.py"
            )
        return 0
    HEADER.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
